version: '2'
services:
  web:
    image: wizzy:latest
    command:  bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    links:
      - db
      - redis
    environment:
      RAILS_ENV: production

  db:
    image: postgres:9.5.4
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: wizzy_production

  worker:
    image: wizzy:latest
    links:
      - db
      - redis
    command: bash -c "bundle exec sidekiq -C ./config/sidekiq.yml"

  redis:
    image: redis:2.8